AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bedrock lambdas

Parameters:
  Env:
    Type: String
    Description: The name of the stage, e.g. "dev", "preprod", "prod"


  pythonversion:
    Description:    Please specify the python version that will be used in all the lambda runtime.
    Type:           String
    Default: python3.9

Resources:

  EventBridgeEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub '${Env}-bedrock-bus'
      Policy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEventsService
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - events:PutEvents
              - events:PutRule
            Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${Env}-bedrock-bus"

  ConvertSchemaFileFormat:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'convert-schema-file-format'
      FunctionName: !Sub '${Env}-convert-schema-file-format'
      CodeUri: ConvertSchemaFileFormat/
      Handler: app.lambda_handler
      Runtime: !Ref pythonversion
      MemorySize: 5120
      Timeout: 900
      Environment:
        Variables:
          DB_HOST: !Sub
            - '{{resolve:ssm:/${Env}/aurora-rds/address/endpoint}}'
            - Env: !Ref Env
          DB_USER: !Sub
            - '{{resolve:ssm:/${Env}/rds/username}}'
            - Env: !Ref Env
          DB_PASSWORD: !Sub
            - '{{resolve:ssm:/${Env}/rds/masteruser/password}}'
            - Env: !Ref Env
          INPUT_TRIGGER_URL: !Sub
            - '{{resolve:ssm:/${Env}/cyzapa/sqs/input-trigger-fifo-queue/url}}'
            - Env: !Ref Env
          DB_PORT: '5432'
          DATABASE: "vec-db"
          INDEX: !Sub '${Env}_index'
          DB_HOST_AOSS: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/opensearch-endpoint}}'
            - Env: !Ref Env
          DB_PORT_AOSS: '443'
          JOB_ID: !Sub "507e43df-032d-404d-a295-1b4eebcba2b5"
          MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
          AWSREGION: !Sub "${AWS::Region}"
          BUCKET: !Sub "${Env}-cymonix-internal"
          QUEUE_NAME: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/sqs/error_fifo_queue/name}}'
            - Env: !Ref Env
      VpcConfig:
        SecurityGroupIds:
          - !Sub
            - '{{resolve:ssm:/${Env}/lambda-graph/sec-grp}}'
            - Env: !Ref Env
        SubnetIds:
          - !Sub
            - '{{resolve:ssm:/${Env}/subnet/privatesubnet1}}'
            - Env: !Ref Env
          - !Sub
            - '{{resolve:ssm:/${Env}/subnet/privatesubnet2}}'
            - Env: !Ref Env
      Layers:
         - !Sub '{{resolve:ssm:/${Env}/layers/arn/error_handler}}'
      Policies:
        - AmazonSQSFullAccess
        - AWSLambdaRole
        - AmazonS3FullAccess
        - AWSLambda_FullAccess
        - AmazonRDSFullAccess
        - AmazonMachineLearningFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'events:PutEvents'
              Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${Env}-bedrock-bus"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'bedrock:InvokeModel'
              Resource: "*"
  #                 - "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-haiku-20240307-v1:0"
  #                 - "arn:aws:bedrock:us-west-2::foundation-model/amazon.titan-embed-text-v1"

  ConvertSchemaFileFormatInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: ConvertSchemaFileFormat
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ConvertSchemaFileFormat
      Principal: s3.amazonaws.com
      SourceArn: !Sub
          - '{{resolve:ssm:/${Env}/cymonix/s3/file_upload/arn}}'
          - StageName: !Ref Env
      SourceAccount:
        Fn::Sub: ${AWS::AccountId}

  ConfigQueueProcessinglambdaArnSSM:
    Type: AWS::SSM::Parameter
    DependsOn: ConvertSchemaFileFormat
    Properties:
      Name:
        Fn::Sub: /${Env}/cymonix/lambda/convertschemafileformat/arn
      Description: 'Holds the ARN for upload Gc Trigger arn'
      Type: String
      Value: !GetAtt ConvertSchemaFileFormat.Arn

  IzzyLikeResponse:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'izzy-like-response'
      FunctionName: !Sub '${Env}-izzy-like-response'
      CodeUri: IzzyLikeResponse/
      Handler: app.lambda_handler
      Runtime: !Ref pythonversion
      MemorySize: 5120
      Timeout: 900
      Environment:
        Variables:
          DB_HOST: !Sub
            - '{{resolve:ssm:/${Env}/aurora-rds/address/endpoint}}'
            - Env: !Ref Env
          DB_USER: !Sub
            - '{{resolve:ssm:/${Env}/rds/username}}'
            - Env: !Ref Env
          DB_PASSWORD: !Sub
            - '{{resolve:ssm:/${Env}/rds/masteruser/password}}'
            - Env: !Ref Env
          DB_PORT: '5432'
          INDEX: !Sub '${Env}_index'
          DB_HOST_AOSS: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/opensearch-endpoint}}'
            - Env: !Ref Env
          DB_PORT_AOSS: '443'
          AWSREGION: !Sub "${AWS::Region}"
          DATABASE: "vec-db"
          INPUT_TRIGGER_URL: !Sub
            - '{{resolve:ssm:/${Env}/cyzapa/sqs/input-trigger-fifo-queue/url}}'
            - Env: !Ref Env
          BUCKET: !Sub "${Env}-cymonix-internal"
          QUEUE_NAME: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/sqs/error_fifo_queue/name}}'
            - Env: !Ref Env
      VpcConfig:
        SecurityGroupIds:
          - !Sub
            - '{{resolve:ssm:/${Env}/lambda-graph/sec-grp}}'
            - Env: !Ref Env
        SubnetIds:
          - !Sub
            - '{{resolve:ssm:/${Env}/subnet/privatesubnet1}}'
            - Env: !Ref Env
          - !Sub
            - '{{resolve:ssm:/${Env}/subnet/privatesubnet2}}'
            - Env: !Ref Env
      Layers:
         - !Sub '{{resolve:ssm:/${Env}/layers/arn/error_handler}}'
      Policies:
        - AmazonSQSFullAccess
        - AWSLambdaRole
        - AmazonS3FullAccess
        - AWSLambda_FullAccess
        - AmazonRDSFullAccess
        - AmazonMachineLearningFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'bedrock:InvokeModel'
              Resource: "*"
  #                 - "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-haiku-20240307-v1:0"
  #                 - "arn:aws:bedrock:us-west-2::foundation-model/amazon.titan-embed-text-v1"

  IzzyLikeResponseLambdaTriggers:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn:
      - IzzyLikeResponse
    Properties:
      Enabled: true
      BatchSize: 1
      EventSourceArn: !Sub
        - '{{resolve:ssm:/${Env}/cymonix/sqs/IzzyLikedResponse_fifo_queue/arn}}'
        - Stage: !Ref Env
      FunctionName:
        Fn::GetAtt:
          - IzzyLikeResponse
          - Arn

  NeptuneOpencypherlambda:
     Type: 'AWS::Serverless::Function'
     Properties:
       Description: 'Lambda to Execute opencypher queries'
       FunctionName: !Sub '${Env}-neptune-opencypher'
       CodeUri: NeptuneOpencypher/
       Handler: app.lambda_handler
       Runtime: !Ref pythonversion
       MemorySize: 256
       Timeout: 300
       Environment:
         Variables:
           QUEUE_URL: !Sub
               - '{{resolve:ssm:/${Env}/cymonix/sqs/bedrockanswer_fifo_queue/url}}'
               - Env: !Ref Env
           CLUSTER_ENDPOINT: !Sub
               - '{{resolve:ssm:/${Env}/neptune/cluster/endpoint}}'
               - Env: !Ref Env
           CLUSTER_PORT: !Sub
               - '{{resolve:ssm:/${Env}/neptune/cluster/port}}'
               - Env: !Ref Env
           BUCKET_NAME: !Sub "${Env}-cymonix-internal"
           MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
           QUEUE_NAME: !Sub
             - '{{resolve:ssm:/${Env}/cymonix/sqs/error_fifo_queue/name}}'
             - Env: !Ref Env
           DISPATCHER_QUEUE_URL: !Sub
              - '{{resolve:ssm:/${Env}/cymonix/sqs/dispatcher_fifo_queue/url}}'
              - Env: !Ref Env
           BEDROCK_REGION: !Sub
             - '{{resolve:ssm:/${Env}/cymonix/bedrock/region}}'
             - Env: !Ref Env

       Layers:
         - !Sub '{{resolve:ssm:/${Env}/layers/arn/error_handler}}'
       VpcConfig:
         SecurityGroupIds:
             - !Sub
               - '{{resolve:ssm:/${Env}/lambda-graph/sec-grp}}'
               - Env: !Ref Env
         SubnetIds:
             - !Sub
               - '{{resolve:ssm:/${Env}/subnet/privatesubnet1}}'
               - Env: !Ref Env
             - !Sub
               - '{{resolve:ssm:/${Env}/subnet/privatesubnet2}}'
               - Env: !Ref Env
       Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AWSLambdaRole
        - AmazonSSMReadOnlyAccess
        - AmazonSQSFullAccess
        - AmazonS3ReadOnlyAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'bedrock:InvokeModel'
              Resource: '*'
       Events:
          MyEventBridgeTrigger:
            Type: CloudWatchEvent
            Properties:
              Pattern:
                source:
                  - !Sub '${Env}-bedrock'
                detail-type:
                  - 'event trigger for bedrock'
                detail:
                  type:
                    - "1"
              EventBusName: !Ref EventBridgeEventBus
       Tags:
          Name: !Sub '${Env}-neptune-opencypher'
          Env: !Sub '${Env}'

  IzzySQLlambda:
     Type: 'AWS::Serverless::Function'
     Properties:
       Description: 'Lambda to generate answers to questions by querying RDS using SQL'
       FunctionName: !Sub '${Env}-izzy-sql'
       CodeUri: IzzySQL/
       Handler: app.lambda_handler
       Runtime: !Ref pythonversion
       MemorySize: 256
       Timeout: 60
       Environment:
         Variables:
           QUEUE_URL: !Sub
               - '{{resolve:ssm:/${Env}/cymonix/sqs/bedrockanswer_fifo_queue/url}}'
               - Env: !Ref Env
           Env: !Sub '${Env}'
           QUEUE_NAME: !Sub
             - '{{resolve:ssm:/${Env}/cymonix/sqs/error_fifo_queue/name}}'
             - Env: !Ref Env
       Layers:
        - !Sub '{{resolve:ssm:/${Env}/layers/arn/error_handler}}'
       VpcConfig:
         SecurityGroupIds:
             - !Sub
               - '{{resolve:ssm:/${Env}/lambda-rds/sec-grp}}'
               - Env: !Ref Env
         SubnetIds:
             - !Sub
               - '{{resolve:ssm:/${Env}/subnet/privatesubnet1}}'
               - Env: !Ref Env
             - !Sub
               - '{{resolve:ssm:/${Env}/subnet/privatesubnet2}}'
               - Env: !Ref Env
       Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AWSLambdaRole
        - AmazonSSMReadOnlyAccess
        - AmazonSQSFullAccess
        - AmazonS3ReadOnlyAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'bedrock:InvokeModel'
              Resource: !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-v2"
       Events:
          MyEventBridgeTrigger:
            Type: CloudWatchEvent
            Properties:
              Pattern:
                source:
                  - !Sub '${Env}-bedrock'
                detail-type:
                  - 'event trigger for bedrock'
                detail:
                  type:
                    - "2"
              EventBusName: !Ref EventBridgeEventBus
       Tags:
          Name: !Sub '${Env}-izzy-sql'
          Env: !Sub '${Env}'

  PromptGeneratorLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'Lambda to generate prompts'
      FunctionName: !Sub '${Env}-prompt-generator'
      CodeUri: PromptGenerator/
      Handler: app.lambda_handler
      Runtime: !Ref pythonversion
      MemorySize: 256
      Timeout: 180
      Environment:
        Variables:
          QUEUE_URL: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/sqs/dispatcher_fifo_queue/url}}'
            - Env: !Ref Env
          Env: !Sub '${Env}'
          QUEUE_NAME: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/sqs/error_fifo_queue/name}}'
            - Env: !Ref Env
          BEDROCK_REGION: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/bedrock/region}}'
            - Env: !Ref Env
      Layers:
        - !Sub '{{resolve:ssm:/${Env}/layers/arn/error_handler}}'
      Policies:
        - AWSLambdaRole
        - AmazonSSMReadOnlyAccess
        - AmazonSQSFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'bedrock:InvokeModel'
              Resource: '*'
      Events:
          MyEventBridgeTrigger:
            Type: CloudWatchEvent
            Properties:
              Pattern:
                source:
                  - !Sub '${Env}-bedrock'
                detail-type:
                  - 'event trigger for bedrock'
                detail:
                  type:
                    - "3"
              EventBusName: !Ref EventBridgeEventBus
      Tags:
        Name: !Sub '${Env}-prompt-generator'
        Env: !Sub '${Env}'

  BedrockAnswerLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'Lambda to generate answers using Bedrock'
      FunctionName: !Sub '${Env}-bedrock-answer-generator'
      CodeUri: BedrockAnswerGenerator/
      Handler: app.lambda_handler
      Runtime: !Ref pythonversion
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          QUEUE_URL: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/sqs/dispatcher_fifo_queue/url}}'
            - Env: !Ref Env
          Env: !Sub '${Env}'
          QUEUE_NAME: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/sqs/error_fifo_queue/name}}'
            - Env: !Ref Env
          BEDROCK_REGION: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/bedrock/region}}'
            - Env: !Ref Env
          BUCKET_NAME: !Sub "${Env}-cym-resource-icons"
          BUCKET_NAME_IN: !Sub "${Env}-cymonix-internal"
          MODEL_ID: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
          MODEL_ID_HQ: "anthropic.claude-3-haiku-20240307-v1:0"
          DB_HOST_AOSS: !Sub
            - '{{resolve:ssm:/${Env}/cymonix/opensearch-endpoint}}'
            - Env: !Ref Env
          DB_PORT_AOSS: '443'
          INDEX: !Sub '${Env}_index'
          IMAGE_LINK: !Sub "${Env}-images.cymonix.net"
      Layers:
        - !Sub '{{resolve:ssm:/${Env}/layers/arn/error_handler}}'
      Policies:
        - AWSLambdaRole
        - AmazonSSMReadOnlyAccess
        - AmazonSQSFullAccess
        - AmazonS3ReadOnlyAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'bedrock:InvokeModel'
                - 'bedrock:InvokeModelWithResponseStream'
              Resource: '*'
            - Effect: Allow
              Action:
                - 's3:PutObject'
              Resource: !Sub 'arn:aws:s3:::${Env}-cym-resource-icons/*'
      Tags:
        Name: !Sub '${Env}-bedrock-answer-generator'
        Env: !Sub '${Env}'

  BedrockAnswerLambdaTriggers:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn:
      - BedrockAnswerLambda
    Properties:
      Enabled: true
      BatchSize: 1
      EventSourceArn: !Sub
        - '{{resolve:ssm:/${Env}/cymonix/sqs/bedrockanswer_fifo_queue/arn}}'
        - Stage: !Ref Env
      FunctionName:
        Fn::GetAtt:
          - BedrockAnswerLambda
          - Arn
